"""Contract/effect regressions. Character fixtures do not prove live support."""

import asyncio
import json
import unittest

import httpx

from research.agent_resume.adapters import FamilyAdapter, UnsupportedTemplate
from research.agent_resume.contracts import InvalidOutput, ToolCalls, UnsupportedOutput
from research.agent_resume.prepare import ScriptedModel
from research.agent_resume.runner import GenerationTransport, run_task
from research.agent_resume.workloads import RepositoryTools, SCHEMA, TASKS
from test_research_harness import FormatFixture, corpus
from toolgap import PrefetchAdmission, PrefetchClient


# Literal external example, not generated by our call_text/ToolCall helper.
# HF Transformers v5.17.0 tool-use guide, generated-output example:
# https://huggingface.co/docs/transformers/v5.17.0/chat_extras
REFERENCE_QWEN = (
    '<tool_call>\n{"arguments": {"location": "Paris, France", '
    '"unit": "celsius"}, "name": "get_current_temperature"}'
    "\n</tool_call><|im_end|>"
)
CALL = '<tool_call>{"name":"search_repository","arguments":{"query":"cleanup_pending"}}</tool_call>'


class TestOutcomes(unittest.TestCase):
    def test_external_reference_has_distinct_completion_and_semantics(self):
        adapter = FamilyAdapter("qwen")
        result = adapter.classify(
            REFERENCE_QWEN, {"get_current_temperature"}, {"type": "stop"}
        )
        self.assertIsInstance(result, ToolCalls)
        self.assertEqual(
            result.calls[0].arguments, {"location": "Paris, France", "unit": "celsius"}
        )
        for finish in (None, "unknown"):
            self.assertIsInstance(
                adapter.classify(REFERENCE_QWEN, {"get_current_temperature"}, finish),
                UnsupportedOutput,
            )
        self.assertEqual(
            adapter.classify(CALL, {"search_repository"}, "length").reason,
            "TRUNCATED_GENERATION",
        )

    def test_multi_calls_are_not_malformed_and_mixed_text_is_not_discarded(self):
        a = FamilyAdapter("qwen")
        self.assertEqual(
            len(a.classify(CALL + "\n" + CALL, {"search_repository"}, "stop").calls), 2
        )
        self.assertIsInstance(
            a.classify(CALL + " Tool passed!", {"search_repository"}, "stop"),
            UnsupportedOutput,
        )
        self.assertIsInstance(
            a.classify(CALL + "<tool_call>{", {"search_repository"}, "stop"),
            InvalidOutput,
        )
        m = FamilyAdapter("mistral")
        raw = '[TOOL_CALLS] [{"name":"t","arguments":{}}]'
        self.assertIsInstance(m.classify(raw, {"t"}, "stop"), ToolCalls)
        self.assertIsNone(m.parse(raw, {"t"}).model_call_id)
        self.assertIsInstance(
            m.classify(raw + " imagined result", {"t"}, "stop"), UnsupportedOutput
        )
        self.assertIsInstance(
            m.classify(raw.replace("{}", "{"), {"t"}, "stop"), InvalidOutput
        )
        self.assertIsInstance(
            m.classify("[TOOL_CALLS]t[ARGS]{}", {"t"}, "stop"), UnsupportedOutput
        )
        self.assertIsInstance(
            a.classify(
                CALL.replace('"arguments":', '"extra":1,"arguments":'),
                {"search_repository"},
                "stop",
            ),
            UnsupportedOutput,
        )

    def test_no_id_has_explicit_history_disposition(self):
        a, t = FamilyAdapter("mistral"), FormatFixture()
        messages = [dict(role="user", content="Question")]
        raw = '[TOOL_CALLS] [{"name":"t","arguments":{}}]'
        call = a.parse(raw, {"t"})
        with self.assertRaisesRegex(UnsupportedTemplate, "MISSING_HISTORY_ID"):
            a.prepare_continuation(
                t, messages, SCHEMA, a.prompt(t, messages, SCHEMA), t.encode(raw), call
            )

    def test_multi_round_append_keeps_actual_noncanonical_tokens(self):
        a, t = FamilyAdapter("qwen"), FormatFixture()
        messages = [dict(role="user", content="Question")]
        ids = a.prompt(t, messages, SCHEMA)
        for raw in (CALL, CALL + "<|im_end|>"):
            generated = t.encode(raw)
            plan = a.prepare_continuation(
                t, messages, SCHEMA, ids, generated, a.parse(raw, {"search_repository"})
            )
            saved = ids + generated
            ids, messages = plan.append(t, dict(matches=[]))
            self.assertEqual(ids[: len(saved)], saved)
            with self.assertRaisesRegex(ValueError, "budget"):
                plan.append(t, dict(matches=[]), max_input_tokens=len(saved))


class TestEffects(unittest.IsolatedAsyncioTestCase):
    async def assert_no_effects(
        self, text, *, tokenizer=None, finish="stop", family="qwen"
    ):
        effects = []

        class Tools(RepositoryTools):
            async def __call__(self, call):
                effects.append("tool")
                return await super().__call__(call)

        class Policy:
            active = None

            async def submit(self, *args, **kwargs):
                effects.append("prefetch")
                raise AssertionError("Unexpected prefetch")

        class Model(ScriptedModel):
            async def generate(self, ids, salt):
                row = await super().generate(ids, salt)
                row["meta_info"]["finish_reason"] = finish
                return row

        async def observe(*args):
            effects.append("observer")

        t = tokenizer or FormatFixture()
        row = await run_task(
            FamilyAdapter(family),
            t,
            Model(t, [text]),
            Tools(corpus()),
            TASKS[0],
            policy=Policy(),
            on_boundary=observe,
        )
        self.assertEqual(row["status"], "FAILED")
        self.assertEqual(row["tools"], [])
        self.assertEqual(effects, [])
        self.assertEqual(row["generations"][0]["raw_text"], text)
        return row

    async def test_broken_history_fails_before_any_effect(self):
        class Changing(FormatFixture):
            def apply_chat_template(self, messages, **kwargs):
                return (
                    "changed" if len(messages) > 2 else ""
                ) + super().apply_chat_template(messages, **kwargs)

        row = await self.assert_no_effects(CALL, tokenizer=Changing())
        self.assertEqual(row["failure_kind"], "UnsupportedContinuation")

    async def test_truncated_mixed_parallel_and_bad_arguments_have_no_effects(self):
        for text, finish in (
            (CALL, "length"),
            (CALL, None),
            (CALL + CALL, "stop"),
            (CALL + " fabricated result", "stop"),
            (CALL.replace('"cleanup_pending"', "true"), "stop"),
        ):
            with self.subTest(text=text, finish=finish):
                await self.assert_no_effects(text, finish=finish)

    async def test_native_no_id_is_unsupported_history_before_effects(self):
        row = await self.assert_no_effects(
            '[TOOL_CALLS] [{"name":"search_repository","arguments":{"query":"KV"}}]',
            family="mistral",
        )
        self.assertEqual(row["generations"][0]["response_outcome"], "ToolCalls")
        self.assertEqual(row["failure_kind"], "UnsupportedContinuation")
        self.assertIn("MISSING_HISTORY_ID", row["error"])

    async def test_execution_identity_does_not_change_model_output(self):
        final = json.dumps(
            dict(
                answer=TASKS[0]["answer"],
                evidence=[dict(path=TASKS[0]["path"], line=1)],
            )
        )
        row = await run_task(
            FamilyAdapter("qwen"),
            FormatFixture(),
            ScriptedModel(FormatFixture(), [CALL, final]),
            RepositoryTools(corpus()),
            TASKS[0],
        )
        self.assertTrue(row["task_success"])
        self.assertIsNone(row["tools"][0]["call"]["model_call_id"])
        self.assertEqual(len(row["tools"][0]["tool_execution_id"]), 32)
        self.assertEqual(row["generations"][0]["raw_text"], CALL)

    async def test_actual_result_overflow_cancels_owned_restore(self):
        admitted = asyncio.Event()
        actions = []

        def handler(request):
            body = json.loads(request.content)
            actions.append(body["action"])
            admitted.set()
            cancel = body["action"] == "cancel"
            return httpx.Response(
                200,
                json=dict(
                    success=True,
                    result=dict(
                        operation_id=body["operation_id"],
                        state="CANCELLED" if cancel else "RUNNING",
                        cleanup_pending=not cancel,
                        restored_tokens=0,
                        restored_bytes=0,
                    ),
                ),
            )

        class LargeResult(RepositoryTools):
            async def __call__(self, call):
                await admitted.wait()
                return dict(text="x" * 12000)

        async with PrefetchClient(
            "http://fixture", transport=httpx.MockTransport(handler)
        ) as client:
            async with PrefetchAdmission(client) as policy:
                row = await run_task(
                    FamilyAdapter("qwen"),
                    FormatFixture(),
                    ScriptedModel(FormatFixture(), [CALL]),
                    LargeResult(corpus()),
                    TASKS[0],
                    policy=policy,
                )
                self.assertEqual(row["status"], "FAILED")
                self.assertIn("budget", row["error"])
                self.assertEqual(len(row["tools"]), 1)
                self.assertIn("result", row["tools"][0])
                self.assertEqual(actions, ["submit", "cancel"])
                self.assertIsNone(policy.active)

    async def test_stream_rewrite_and_missing_terminal_are_rejected(self):
        for body in (
            'data: {"output_ids":[1]}\n\ndata: {"output_ids":[2],"meta_info":{"finish_reason":{"type":"stop"}}}\n\n',
            'data: {"output_ids":[1]}\n\ndata: [DONE]\n\n',
        ):
            async with httpx.AsyncClient(
                base_url="http://fixture",
                transport=httpx.MockTransport(lambda _: httpx.Response(200, text=body)),
            ) as http:
                with self.assertRaises(ValueError) as raised:
                    await GenerationTransport(http).generate([8], "salt")
                self.assertEqual(
                    raised.exception.generation_evidence["output_ids"], [1]
                )
                self.assertTrue(raised.exception.generation_evidence["stream_events"])
